# Generated by Django 4.2.5 on 2024-05-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member_data',
            fields=[
                ('member', models.AutoField(primary_key=True, serialize=False)),
                ('member_account', models.CharField(max_length=200, unique=True)),
                ('member_password', models.CharField(max_length=200)),
                ('gmail', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('show', models.CharField(choices=[('coming_soon', '即將上映'), ('showing', '現正熱映'), ('removed', '下架電影')], max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_number', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymovie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_data',
            fields=[
                ('staff', models.AutoField(primary_key=True, serialize=False)),
                ('staff_password', models.CharField(max_length=200)),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_department', models.CharField(choices=[('it', 'IT部門'), ('hr', '人事部門')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('money', '現金'), ('credit_card', '信用卡')], max_length=100)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymovie.session')),
                ('ticket_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymovie.member_data')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='change_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymovie.staff_data'),
        ),
    ]
