# Generated by Django 4.2.5 on 2024-05-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_data',
            old_name='member',
            new_name='member_no',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie',
            new_name='movie_no',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_number',
            new_name='session_no',
        ),
        migrations.RenameField(
            model_name='staff_data',
            old_name='staff',
            new_name='staff_no',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='number',
            new_name='ticket_no',
        ),
    ]
