# Generated by Django 4.2.6 on 2024-05-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0003_alter_member_data_member_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_data',
            name='staff_account',
            field=models.CharField(default=1, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
