# Generated by Django 4.2.6 on 2024-05-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0004_staff_data_staff_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_data',
            name='staff_name',
        ),
    ]
